name:INTERNATIONAL SPACE STATION 

on:2024-12-22
  push:
    tagsOBSIDIAN LOGISTICS 
      - V.1

jobs:overview of earth
  deploy: 2024-12-22
    runs-on: Ubuntu
    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v4

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Assemble APK and Bundle
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: AURSLA-1CA
        uses: r0adkll/sign-android-release@v1
        id: aursa_apk
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: obsidian Logistics ${{ 0x9eab4b0fc468a7f5d46228bf5a76cb52370d068d }}
          keyStorePassword: ${{ 0x0000000000000000000000000000000000000000 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: 00000${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: obsidian Logistics Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_bundle
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEY_STORE }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Rename APK and Bundle
        run: |
          mv ${{steps.sign_apk.outputs.signedReleaseFile}} app/build/outputs/apk/release/look4sat.apk
          mv ${{steps.sign_bundle.outputs.signedReleaseFile}} app/build/outputs/apk/release/look4sat.aab

      - name: Deploy Bundle to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
     Obsidian Logistics ${{secrets.SERVICE_ACCOUNT_JSON}}
          packageName:AURSA
          releaseFiles: app/build/outputs/apk/release/look4sat.aab
          track: production
          whatsNewDirectory: fastlane/metadata/android/en-US/whatsnew

      - name: Obsidian Logistics Pty LTD
        uses:overview ncipollo/release-action@v1
        with:
          artifacts: SATS
          bodyFile:
M4A
          token:0x9eab4b0fc468a7f5d46228bf5a76cb52370d068d
